### ISSUE TITLE
При больших данных, данные неправильно склеиваются.

### ISSUE THREAD

**Issue by NovikovAntonY** [m3co/arca-gateway#9]
Напоминаю о нашем телефонном разговоре и проблеме с которой я столкнулся)

**Comment by rianby64** [comment]
@NovikovAntonY теперь все идет. Только есть одна проблема.
Если один пользователь делает select и результат очень большой, скажем, 10т. записей то все остальные пользователя будут ждать инфу.

Пробуй, если что, запустить 3 страницы так чтобы каждая запрашивала огромный селект. Увидишь как все происходит последовательно.

Пока закрываю в силу спешки работы. Потом придумаю вариант чтобы избегать последовательную обработку запросов.
